spring:
  datasource:
    url: jdbc:mysql://localhost:3306/karrot_market?serverTimezone=Asia/Seoul
    username: root
    password: root1234
    admin:
    jdbc: com.mysql.cj.jdbc.Driver
  jpa:
    generate-ddl: true # flyway를 적용하려면 ddl 기능 false로 해야한다.
    hibernate:
      ddl-auto: update # flyway를 사용하기위해 validate 설정값으로 변경한다.
    show-sql: true
    properties:
      hibernate:
        format_sql: true
#  flyway:
#    enabled: true
#    baseline-on-migrate: true
#    locations: classpath:db/migration, classpath:db/seed # Flyway 경로 설정
